Revert "Prevent memcached from seeing a negative delta for incr/decr"
This reverts commit 6fbdd3cca4158e24e8e6c44a9042b943c8671b65.

The patched version of memcached that Less Wrong uses does not raise an
error under these conditions. This commit also broke meetups creation
due to:

Module r2.controllers.meetupscontroller:83 in POST_create
>>  g.rendercache.invalidate_key_group(Meetup.group_cache_key())
Module r2.lib.cache:61 in invalidate_key_group
>>  self.incr(prefix)
TypeError: incr() takes exactly 3 arguments (2 given)